### ISSUE TITLE
Importing error and solution (along with Lindblad equations in qubricks)

### ISSUE THREAD

**Issue by iScienceLuvr** [matthewwardrop/python-qubricks#1]
I tried to install qubricks but I got importing errors for the parameters module. I realized the problem was that in the code, the importing was done like this:

`from parameters import Parameters`
There is no class called Parameters. It is called Parameter. I uninstalled qubricks, fixed the code by deleting the 's' in " Parameters" and re installed. It worked. ALso, note that I needed to also install mako since in integratorcallback.py it requires mako.templates. Maybe you should make that a dependency.

**Comment by matthewwardrop** [comment]
Hi iScienceLover.

Thanks for your interest in QuBricks :). Be careful, though; since QuBricks definitely does require `Parameters`; which is part of my python-parameters library. Unfortunately, there is another project (predating mine) which is called "parameters".

You can find python-parameters at: https://github.com/matthewwardrop/python-parameters .

Best,
M

**Comment by iScienceLuvr** [comment]
Thanks, also do you have a function to solve lindblad equations? I know there are some functions for open quantum systems and such (you do have a class for single termed lindblad equations), but haven't found a way to solve lindblad master equations.

**Comment by matthewwardrop** [comment]
No worries. The example given in the opening pages of documentation.pdf (and in my python-qubricks-examples repository) is exactly that, is it not?

**Comment by iScienceLuvr** [comment]
@matthewwardrop this isn't clear? what equation are u solving in that example? I am solving 
$$\dot\rho=-{i\over\hbar}[H,\rho]+\sum_{n,m = 1}^{N^2-1} h_{n,m}\left(L_n\rho L_m^\dagger-\frac{1}{2}\left(\rho L_m^\dagger L_n + L_m^\dagger L_n\rho\right)\right)$$

**Comment by matthewwardrop** [comment]
The listed example solves:
$$\dot\rho=-{i\over\hbar}[H,\rho]+ h\left(L\rho L^\dagger-\frac{1}{2}\left(\rho L^\dagger L + L^\dagger L\rho\right)\right)$$

In general, each of the `StateOperator` objects in `derivative_ops` is applied to the state `p` using their `apply` method at each step in the integration, and the result is summed. The `SchrodingerStateOperator` is automatically added with the name of "evolution". The `SchrodingerStateOperator` effects the first additive term in the above equation, and the `LindbladStateOperator` effects the second term.

Does that make sense?

**Comment by iScienceLuvr** [comment]
@matthewwardrop Thanks, is there a way to multiply the `LindbladStateOperator` by a constant? Is that what `(coefficient='D'` means in `LindbladStateOperator(coefficient='D',operator=[[0,1],[1,0]])` as in the example?

**Comment by matthewwardrop** [comment]
Yeah... In the code you cited, h='D'  and L = [[0,1],[1,0]](Pauli X); and
where 'D' is a parameter stored in the Parameters instance.

**Comment by iScienceLuvr** [comment]
@matthewwardrop wait, so coefficient D is equal to h, Planck's constant? And L is the Lindblad operator (in this case, Pauli X)?

**Comment by matthewwardrop** [comment]
No no... I said that the example solves:

$$\dot\rho=-{i\over\hbar}[H,\rho]+ h\left(L\rho L^\dagger-\frac{1}{2}\left(\rho L^\dagger L + L^\dagger L\rho\right)\right)$$

The h in this equation (which is a coefficient of the Lindblad superoperator) is the 'coefficient' keyword argument to the LindbladStateOperator. The 'operator' keyword specifies L.

**Comment by iScienceLuvr** [comment]
@matthewwardrop ok, i get it.. How reliable and fast would your module be for solving a Lindblad equation with 7 sites (therefore, 7x7 matrices for Hamiltonian, Lindblad operators, and obviously rho)?

**Comment by matthewwardrop** [comment]
Very reliable; and, depending on the complexity of the time-dependencies of your parameters, very fast. I routinely integrate 64x64 and larger systems.

**Comment by iScienceLuvr** [comment]
@matthewwardrop thanks

**Comment by matthewwardrop** [comment]
No worries. Drop me an email (mister.wardrop@gmail.com) if you have any troubles or want more help. I'd love to get others using my work.

**Comment by iScienceLuvr** [comment]
@matthewwardrop BTW, what is expectationmeasurement? what does it do and how do I use it? is it needed to use the integrate function?

**Comment by matthewwardrop** [comment]
`ExpectationMeasurement` is a subclass of the `Measurement` class, from which it inherits a lot of power. See the API documentation of `MeasurementWrapper` for how to deal with the: `QuantumSystem.measure.<name of measurement>` object.

Simply, the `ExpectationMeasurement` computes the expectation value of a certain measurement operator based on the current state. In this sense, it is non-physical, since to generate the expectation value in a real experiment, you would have to run the simulation many times (depending on the precision required). Given access to the wavefunction, as I presume you know, we can easily compute the expectation value as: `<x|O|x>` . That's what this object does.

So, if we construct an `ExpectationMeasurement` object, like:

```
>>> m = ExpectationMeasurement(<matrix/array/Operator 1>, <matrix/array/Operator 2>, ..)
```

Then when `m.measure` is called, it will return the expectation value of the operator with the simulated state.

If a measurement is not specified, you can still use the `integrate` method; and perform any analysis you like. See the API documentation for `QuantumSystem.integrate`.

If you send me a description of the problem you'd like to solve, I'll code up the basics of it for you; so you can see how QuBricks works.

**Comment by iScienceLuvr** [comment]
@matthewwardrop do these functions work with symbolic variables? the Integrator class, which I know the QuantumSystem.integrate function is based of, seems to be only available for numerical calculations...

**Comment by iScienceLuvr** [comment]
@matthewwardrop I have a Hamiltonian:

`[[e1,V12,V13,V14,V15,V16,V17],[V12,e2,V23,V24,V25,V26,V27],[V13,V23,e3,V34,V35,V36,V37],[V14,V24,V34,e4,V45,V46,V47],[V15,V25,V35,V45,e5,V56,V57],[V16,V26,V36,V46,V56,e6,V67],[V17,V27,V37,V47,V57,V67,e7]]`

I want to find the density matrix function of time. I don't want to do a measurement. If you are going to do an example, I don't care what Lindblad operator you use (Although the Lindblad operators matrices with a 1 at the mm site and 0 everywhere else for m=1 to 7. Therefore, to implement this, there would need to be 7 `LindbladStateOperator` instances for m=1 to 7). The initial density matrix is the outer product of the ground state. Thanks.

**Comment by matthewwardrop** [comment]
The Integrator class can definitely handle symbolic variables; but only in order to transform them into numerical values for the integration. Symbolic integration of operators is not possible (nor really sensible when you start looking at decoherence with Lindblad terms). Do you still want an example written for your problem with the above limitations?

**Comment by iScienceLuvr** [comment]
@matthewwardrop I just want the components in the Hamiltonian matrix to be symbolic.. if that is not possible, I don't care what those constants are...Thanks
